crm项目/完成公私户 分页/Pro_crm/Pro_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/', include('crm.urls'))

]

crm项目/完成公私户 分页/Pro_crm/crm/urls.py
from django.conf.urls import url
from crm import views
urlpatterns =[
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^index/', views.index, name='index'),
    url(r'^customer_list/', views.customer, name='customer'),
    url(r'^add_customer/', views.customer_change, name='add_customer'),
    url(r'^edit_customer/(\d+)/', views.customer_change, name='edit_customer'),
]

crm项目/完成公私户 分页/Pro_crm/crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)


class UserProfile(models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", )

    def show_class(self):
        return ','.join([str(i) for i in self.class_list.all()])

    def show_status(self):
        get_dic = {'signed': "btn-primary",
                    'unregistered': "btn-danger",
                    'studying': 'btn-warning',
                    'paid_in_full': "btn-success"}

        return mark_safe('<span style="padding:8px" class="{}">{}</span>'.format(get_dic[self.status], self.get_status_display()))


    def __str__(self):
        return self.name


class Campus(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campus', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return '{}-{}'.format(self.get_course_display(), self.semester)



class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campus')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级", related_name='cl_record')
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师", related_name='te_record')
    recorder = models.ForeignKey('UserProfile', verbose_name="记录者")

    class Meta:
        unique_together = ('re_class', 'day_num')


class StudyRecord(models.Model):
    """
    学习记录
    """

    attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.CharField("备注", max_length=255, blank=True, null=True)

crm项目/完成公私户 分页/Pro_crm/crm/forms.py
import hashlib
from crm import models
from django import forms
from django.core.exceptions import ValidationError
from multiselectfield.forms.fields import MultiSelectFormField

class RegForm(forms.ModelForm):
    password = forms.CharField(min_length=6,
                              widget=forms.PasswordInput(attrs={
                                'placeholder': '您的密码',
                                'autocomplete': 'off'}))
    re_password = forms.CharField(min_length=6,
                              widget=forms.PasswordInput(attrs={
                                'placeholder': '您的密码',
                                'autocomplete': 'off'}))

    class Meta:
        model = models.UserProfile
        fields ='__all__'
        exclude = ['is_alive']
        widget = {
            'username': forms.EmailInput(attrs={'placeholder': '您的邮箱名', 'autocomplete': 'off'}),
            'mobile': forms.TextInput(attrs={'placeholder': '您的手机号码', 'autocomplete': 'off'}),
            'name':forms.TextInput(attrs={'placeholder': '您的真实姓名', 'autocomplete': 'off'})
        }

    def clean(self):
        self._validate_unique = True
        password =self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')
        if password == re_password:
            md5 = hashlib.md5()
            md5.update(password.encode('utf-8'))
            self.cleaned_data['password'] = md5.hexdigest()
            return self.cleaned_data
        else:
            self.add_error('password', '两次密码输入不一致')
            raise ValidationError('密码输入不一致')


class Customer_form(forms.ModelForm):

    class Meta:
        model = models.Customer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():

            if isinstance(field,MultiSelectFormField):
                continue
            field.widget.attrs['class'] = 'form-control'






        # exclude = ['last_consult_date']
        # widgets = {
        #     'qq': forms.EmailInput(attrs={'placeholder': 'QQ号码', 'autocomplete': 'off',
        #                                   'class':'form-control'}),
        #     'qq_name': forms.TextInput(attrs={'placeholder': 'QQ昵称', 'autocomplete': 'off',
        #                                       'class':'form-control'}),
        #     'name':forms.TextInput(attrs={'placeholder': '真实姓名', 'autocomplete': 'off',
        #                                   'class':'form-control'}),
        #     'phone':forms.TextInput(attrs={'placeholder': '手机号', 'autocomplete': 'off',
        #                                    'class':'form-control'}),
        #     'source':forms.Select(attrs={'placeholder': '来源', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'introduce_from':forms.TextInput(attrs={'placeholder': '推荐您来的学员(选填)', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'course':forms.SelectMultiple(attrs={'placeholder': '咨询课程', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'class_type':forms.Select(attrs={'placeholder': '班级', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #
        #     'status':forms.Select(attrs={'placeholder': '当前状态', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'next_date':forms.DateInput(attrs={'placeholder': '预计再次跟进时间,格式yyyy-mm-dd', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'consultant':forms.Select(attrs={'placeholder': '所属销售', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'class_list':forms.SelectMultiple(attrs={'placeholder': '已报班级', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'customer_note':forms.TextInput(attrs={'placeholder': '客户备注', 'autocomplete': 'off',
        #                                     'class':'form-control'}),
        #     'sex':forms.Select(attrs={'placeholder': '性别', 'autocomplete': 'off',
        #                                     'class':'form-control'})
        # }

crm项目/完成公私户 分页/Pro_crm/crm/views.py
import hashlib
from crm import models
from utils.paginator import paginator
from crm.forms import RegForm, Customer_form
from django.shortcuts import render, HttpResponse, redirect, reverse



def login(request):
    if request.session.get('is_login'):
        request.session.flush()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        md5 = hashlib.md5()
        md5.update(password.encode('utf-8'))
        obj = models.UserProfile.objects.filter(username=username, password=md5.hexdigest(), is_active=True).first()
        if obj:
            request.session['is_login'] = True
            request.session['user_id'] = obj.pk
            return redirect(reverse('customer'))
        else:
            return render(request, 'login.html', {'error': '用户名或密码错误'})
    return render(request, 'login.html')



def register(request):
    form_obj = RegForm()
    if request.method == 'POST':
        form_obj = RegForm(request.POST)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('login'))
    return render(request, 'reg.html', {'form_obj': form_obj})



def index(request):
    return HttpResponse('你成功进入')



def customer(request):
    if not request.session.get('is_login'):
        all_customer = models.Customer.objects.filter(consultant_id__isnull=True)
    else:
        all_customer = models.Customer.objects.filter(consultant_id=request.session['user_id'])

    res = paginator(request.GET.get('page', 1), all_customer)
    return render(request, 'customer_list.html', {'all_customer': all_customer[res.start_data:res.end_data], 'page': res.page_html})


# def add_customer(request):
#     form_obj = Customer_form()
#     if request.method == 'POST':
#         form_obj = Customer_form(request.POST)
#         if form_obj.is_valid():
#             form_obj.save()
#             return redirect(reverse('customer'))
#     return render(request, 'add_customer.html', {'form_obj': form_obj})


def customer_change(request, pk=None):
    if request.session.get('is_login'):
        start_obj = models.Customer.objects.filter(pk=pk).first()
        form_obj = Customer_form(instance=start_obj)
        if request.method == 'POST':
            form_obj = Customer_form(data=request.POST,instance=start_obj)
            if form_obj.is_valid():
                form_obj.save()
                return redirect(reverse('customer'))
        title = '编辑客户' if pk else '新建用户'
        return render(request, 'customer_change.html', {'form_obj': form_obj, 'title': title})
    else:
        return redirect(reverse('login'))

crm项目/完成公私户 分页/Pro_crm/crm/templates/add_customer.html
{% extends 'layout.html' %}
{% block content %}
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2" style="margin-top: 10px">
            <div class="panel panel-primary text-center">
                <div class="panel-heading ">
                    <h3 class="panel-title ">新增客户</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form_obj.name.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.name.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.name }}{{ form_obj.name.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.sex.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.sex.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.sex }}{{ form_obj.sex.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.qq.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.qq.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.qq }}{{ form_obj.qq.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.qq_name.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.qq_name.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.qq_name }}{{ form_obj.qq_name.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.obj.phone.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.phone.label }} </label>
                            <div class="col-sm-7">
                                {{ form_obj.phone }}{{ form_obj.phone.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.source.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.source.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.source }}{{ form_obj.source.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.introduce_from.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.introduce_from.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.introduce_from }}{{ form_obj.introduce_from.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.course.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.course.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.course }}{{ form_obj.course.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.class_type.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.class_type.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.class_type }}{{ form_obj.class_type.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.status.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.status.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.status }}{{ form_obj.status.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.next_date.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.next_date.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.next_date }}{{ form_obj.next_date.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.consultant.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.consultant.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.consultant }}{{ form_obj.consultant.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.class_list.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.class_list.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.class_list }}{{ form_obj.class_list.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form_obj.customer_note.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.customer_note.label }}</label>
                            <div class="col-sm-7">
                                {{ form_obj.customer_note }}{{ form_obj.customer_note.errors.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-1 col-sm-10">
                                <button type="submit" class="btn btn-primary" style="margin-top: 13px;margin-bottom: -15px">提交</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

crm项目/完成公私户 分页/Pro_crm/crm/templates/customer_change.html
{% extends 'layout.html' %}
{% block content %}
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2" style="margin-top: 10px">
            <div class="panel panel-primary ">
                <div class="panel-heading ">
                    <h3 class="panel-title ">{{ title }}</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="" novalidate>
                        {% csrf_token %}
                        {% for field in form_obj %}
                            <div class="form-group {% if field.errors %}has-error{% endif %}">
                                <label {% if not field.field.required %} style="color: #777777" {% endif %} for="{{ field.id_for_label }}"
                                       class="col-sm-3 control-label">{{ field.label }}</label>
                                <div class="col-sm-7">
                                    {{ field }}
                                    <span class="help-block">{{ field.errors.0 }}</span>
                                </div>
                            </div>

                        {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-1 col-sm-10">
                                <button type="submit" class="btn btn-primary"
                                        style="margin: 0 227px;">提交
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

crm项目/完成公私户 分页/Pro_crm/crm/templates/customer_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading" style="text-align: center;"><h2>学生信息主页</h2></div>
        <div class="panel-body" id="box">
            <a href="" style="color: white">
                <a class="btn btn-primary" href="{% url 'add_customer' %}">录入学生信息</a>
            </a>
            <table class="table table-striped table-hover text-center">
                <thead>
                <tr>
                    <th style="text-align: center">序号</th>
                    <th style="text-align: center">ID</th>
                    <th style="text-align: center">姓名</th>
                    <th style="text-align: center">性别</th>
                    <th style="text-align: center">qq</th>
                    <th style="text-align: center">出生日期</th>
                    <th style="text-align: center">手机号</th>
                    <th style="text-align: center">客户来源</th>
                    <th style="text-align: center">咨询课程</th>
                    <th style="text-align: center">班级类型</th>
                    <th style="text-align: center">状态</th>
                    <th style="text-align: center">下次跟进时间</th>
                    <th style="text-align: center">销售</th>
                    <th style="text-align: center">已报班级</th>
                    <th style="text-align: center">操作</th>
                </tr>
                </thead>
                <tbody id="UserList">
                {% csrf_token %}
                {% for customer in all_customer %}
                    <tr>
                        <td style="vertical-align: inherit">{{ forloop.counter }}</td>
                        <td style="vertical-align: inherit">{{ customer.pk }}</td>
                        <td style="vertical-align: inherit">{{ customer.name }}</td>
                        <td style="vertical-align: inherit">{{ customer.get_sex_display }}</td>
                        <td style="vertical-align: inherit">{{ customer.qq }}</td>
                        <td style="vertical-align: inherit">{{ customer.birthday }}</td>
                        <td style="vertical-align: inherit">{{ customer.phone }}</td>
                        <td style="vertical-align: inherit">{{ customer.get_source_display }}</td>
                        <td style="vertical-align: inherit">{{ customer.course }}</td>
                        <td style="vertical-align: inherit">{{ customer.get_class_type_display }}</td>
                        <td style="vertical-align: inherit">{{ customer.show_status }}</td>
                        <td style="vertical-align: inherit">{{ customer.next_date }}</td>
                        <td style="vertical-align: inherit">{{ customer.consultant|default:'无' }}</td>
                        <td style="vertical-align: inherit">{{ customer.show_class|default:'无' }}</td>
                        <td style="vertical-align: inherit">
                            <a href="{% url 'edit_customer' customer.pk %}" class="btn btn-primary btn-sm">修改</a>
                            <a href="" class="btn btn-danger btn-sm">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation" class="text-center" style="margin-top: 250px">
                <ul class="pagination">
                    {{ page }}
                </ul>
                <div class="pageJump">
                    <form action="">
                        <span>跳转到</span>
                        <input type="number" name="page" style="width: 70px">
                        <span>页</span>
                        <button class="button" >确定</button>
                    </form>
                </div>

            </nav>
        </div>
    </div>


{% endblock %}